apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None # Headless svc.
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet # Can only exposed by headless svc.
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx" # Should be the same as headless svc name.
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: hub.atguigu.com/library/myapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www # Should be the same as PVC name.
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates: # PVC
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce"] # Used to match PV
      storageClassName: "nfs" # Used to match PV
      resources:
        requests:
          storage: 1Gi 
