- name: install mysql8.0
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - epel-release
    - mysql-community-server
    - mysql-community-client
    - python-PyMySQL
    - MySQL-python