---
- name: 创建数据目录
  file: dest={{ zk_datadir }} state=directory

- name: 解压 kafka 压缩包
  unarchive: 
    src: "{{ item }}"
    dest: "{{ work_dir }}"
    creates: "{{ work_dir }}/{{ kafka_un_name }}"
  with_fileglob:
    - "{{ tmp_dir }}/{{ kafka_zip_name }}"

- name: 分发 kafka 配置文件
  template: src=server.properties.j2 dest={{ work_dir }}/{{ kafka_un_name }}/config/server.properties

- name: 修改 kafka JVM 配置
  replace:
    path: "{{ work_dir }}/{{ kafka_un_name }}/bin/kafka-server-start.sh"
    regexp: '(.*) export KAFKA_HEAP_OPTS=(.*)'
    replace: '\1 export KAFKA_HEAP_OPTS="-Xmx{{ kafka_mem }} -Xms{{ kafka_mem }}"'

- name: 设置 kafka 环境变量
  lineinfile:
    dest: /etc/profile
    line: "{{ item }}"
  with_items:
    - "KA_BIN={{ work_dir }}/{{ kafka_un_name }}/bin"
    - "PATH=$KA_BIN:$PATH"
    
- name: 配置生效
  raw: source /etc/profile

- name: 分发service文件
  template: src=kafka.service.j2 dest=/usr/lib/systemd/system/kafka.service
    
- name: 启动kafka
  systemd: name=kafka state=started enabled=yes daemon_reload=yes
