version: '3'
services:
  nginx:
    hostname: nginx
    image: nginx:1.19.5
    ports:
      - "80:80"
    links:
      - php:php-cgi
    volumes:
      - ./wwwroot:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: bridge

  php:
    hostname: php
    image: phpdockerio/php73-fpm
    links:
      - mysql:mysql-db
    volumes:
      - ./wwwroot:/usr/share/nginx/html
      - ./php/php.ini:/etc/php/7.3/fpm/php.ini
      - ./php/php-fpm.d/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
    network_mode: bridge

  mysql:
    hostname: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    network_mode: bridge

  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin
    ports:
      - "8088:80"
    links:
      - mysql:mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    network_mode: bridge