- name: install repo
  yum: name=https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm state=present

- name: config zabbix repo from aliyun
  copy: src=zabbix.repo dest=/etc/yum.repos.d/

- name: install zabbix-agent
  yum: name=zabbix-agent state=present