---

- name: Set en_US.UTF-8
  template: src=locale.conf.j2 dest=/etc/locale.conf backup=yes

- name: Change rc.local Mode
  file: path=/etc/rc.d/rc.local mode=0755

- name: setting timezone
  shell: "timedatectl set-timezone Asia/Shanghai"

- name: Change hostname
  shell: "hostnamectl set-hostname {{hostname|quote}}"
  when: hostname is defined