---
- name: add aliyun base repo
  copy:
    src: CentOS-Base-aliyun.repo
    dest: "/etc/yum.repos.d/CentOS-Base.repo"
    backup: yes

- name: add aliyun epel repo
  copy:
    src: epel-aliyun.repo
    dest: "/etc/yum.repos.d/epel.repo"
    backup: yes

- name: yum makecache
  raw: "{{ item }}"
  with_items:
    - "yum clean all"
    - "yum makecache fast -y"