- name: render and copy nginx config
  template:
    src: nginx.conf.j2
    dest: /app/nginx/conf
    backup: true
    validate: "/app/nginx/sbin/nginx -t -c %s"
  notify: "reload nginx"

- name: nginx vhost config
  include_tasks: vhost_config.yml
  loop: "{{ vhosts|dict2items }}"
  loop_control:
    extended: yes