apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
spec:
  containers:
  - image: hub.atguigu.com/library/myapp:v1
    name: empty-dir-cn
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - name: liveness-exec-cn
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "sleep 6000s"] 
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
