- name: install zabbix repo
  yum: name=https://mirrors.aliyun.com/zabbix/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm state=present

- name: config zabbix repo
  copy: src=zabbix.repo dest=/etc/yum.repos.d/

- name: install zabbix server
  yum: name=zabbix-server-mysql state=present

- name: install zabbix agent
  yum: name=zabbix-agent state=present

- name: install Software Collections
  yum: name=centos-release-scl state=present

- name: install zabbix frontend
  yum: name=zabbix-web-mysql-scl state=present

- name: install zabbix-apache-conf-scl
  yum: name=zabbix-apache-conf-scl state=present

- name: install epel
  yum: name=epel-release state=present

- name: install python-PyMySQL
  yum: name=python-PyMySQL state=present

- name: install MySQL-python
  yum: name=MySQL-python state=present

- name: install mariadb
  yum: name=mariadb-server state=present