# kubectl create secret docker-registry my-docker-registry --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-emai=DOCKER_EMAIL

apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
  - name: foo
    image: hub.atguigu.com/my-hub/myapp:v2
  imagePullSecrets:
  - name: my-docker-registry
