apiVersion: v1
kind: Service
metadata:
  name: headless-svc
  namespace: default
spec:
  selector:
    app: myapp
    release: stable
  clusterIP: "None"
  ports:
  - name: http
    port: 80
    targetPort: 80
