---
handlers:
  - name: restart redis
    systemd: name=redis state=restarted

- name: Add master auth
  lineinfile:
    path: "{{ REDIS_CONF_DIR }}/redis.conf"
    line: "masterauth {{ MASTER_PASS }}" 
  notify:
  - restart redis

- name: Config slave redis
  lineinfile:
    path: "{{ REDIS_CONF_DIR }}/redis.conf"
    line: "slaveof {{ REDIS_MASTER_IP }} {{ REDIS_CONFIG['PORT'] }}"
  when: "{{ansible_all_ipv4_addresses}}" != "{{ REDIS_MASTER_IP }}"

- name: Change bin 0.0.0.0
  lineinfile:
    path: "{{ REDIS_CONF_DIR }}/redis.conf"
    regexp: '^bind'
    line: 'bind 0.0.0.0'

- name: Copy sentinel config
  template:
    src: sentinel.conf.j2
    dest: "{{ REDIS_CONF_DIR }}/sentinel.conf"

- name: Config sentinel systemd
  template: src=redis-sentinel.service.j2 dest=/usr/lib/systemd/system/redis-sentinel.service

- name: Start redis-sentinel service
  systemd: name=redis-sentinel state=restarted enabled=yes daemon_reload=yes