---
# DaemonSet除了不用设置replicas，其他的与Deployment一致。
apiVersion: apps/v1      #必填，版本号
kind: DaemonSet     #必填，资源类型
metadata:       #必填，元数据
  name: <name>-ds     #必填，资源名称
  namespace: <namespace>    #Pod所属的命名空间
  labels:      #自定义标签
    - name: string     #自定义标签名字<key: value>
spec:         #必填，部署的详细定义
  selector: #必填，标签选择
    matchLabels: #必填，标签匹配
      name: <name> #必填，通过此标签匹配对应pod<key: value>
  template: #必填，应用容器模版定义
    metadata: 
      labels: 
        name: <name> #必填，与上面matchLabels的标签相同
    spec: 
      containers: #此处参考pod的containers