---
aVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  labels:
    name: myapp-ingress
spec:
  tls:
  - hosts:
    - myapp.test.com
    secretName: myapp-tls-secret
  rules:
  - host: myapp.test.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: myapp-svc
            port: 
              number: 80