---
apiVersion: v1 # 必填，版本号
kind: Secret # 必填，资源类型
metadata: # 必填，元数据
  name: <name>-cm # 必填，资源名称
  namespace: string # 资源命名空间
type: Opaque # 必填，secret数据类型标识。Opaque：base64 编码格式的 Secret，用来存储密码、密钥等。kubernetes.io/dockerconfigjson：用来存储私有docker registry的认证信息。kubernetes.io/service-account-token：用于被serviceaccount引用，serviceaccout 创建时Kubernetes会默认创建对应的secret
data: # 必填，保存的数据信息
  key: value # 数据信息