---
- name: add ipvs modules 
  shell: "{{ item }}"
  with_items:
    - "modprobe -- ip_vs"
    - "modprobe -- ip_vs_rr"
    - "modprobe -- ip_vs_wrr"
    - "modprobe -- ip_vs_sh"
    - "modprobe -- nf_conntrack_ipv4"

- name: install ipvs tools
  package:
    name:
      - nfs-utils
      - ipset
      - ipvsadm
    state: latest