- name: Install Nginx Depend on the package
  yum: name={{ item }} state=present
  loop:
  - openssl
  - openssl-devel
  - pcre
  - pcre-devel
  - gcc
  - gcc-c++
  - automake
  - zlib
  - zlib-devel

- name: Install Nginx package
  copy: src=nginx-{{ version }}.tar.gz dest=/usr/local/src/

- name: Add user nginx
  user: name=nginx shell=/bin/false createhome=no state=present

- name: Install Nginx
  shell: cd /usr/local/src/ && tar xf nginx-{{ version }}.tar.gz && cd nginx-{{ version }} && ./configure --prefix=/usr/local/nginx --conf-path=/etc/nginx/nginx.conf --user=nginx --group=nginx --error-log-path=/var/log/nginx/error_log --http-log-path=/var/log/nginx/access_log --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module && make && make install && ln -s /usr/local/nginx/sbin/nginx /usr/sbin/nginx

# - name: Install Nginx env
#   copy: src=nginx.sh dest=/etc/profile.d/

- name: Copy systemd file
  copy: src=nginx.service dest=/lib/systemd/system/nginx.service

- name: Create conf.d and website root
  shell: mkdir -p "/apps/site/{{ domain_name }}" && mkdir /etc/nginx/conf.d

- name: Copy index.html file
  copy: src=index.html dest="/apps/site/{{ domain_name }}"

- name: Add nginx config file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Add nginx default config file
  template: src=default_server.conf.j2 dest=/etc/nginx/conf.d/default_server.conf

- name: Add nginx website config file
  template: src=www.conf.j2 dest=/etc/nginx/conf.d/www.conf

- name: Add nginx status config file
  template: src=status.conf.j2 dest=/etc/nginx/conf.d/status.conf

- name: Restart nginx service
  systemd: name=nginx daemon_reload=yes state=restarted

