- name: install packages
  shell: yum install -y epel-release && \
         yum install -y gc gcc gcc-c++ \
         pcre-devel zlib-devel wget \
         openssl openssl-devel zlib-devel \
         libxml2 libxml2-devel bzip2-devel libmcrypt-devel \
         sqlite-devel glibc glibc-devel pcre pcre-devel \
         systemd-devel net-tools iotop bc zip unzip zlib-devel bash-completion \
         nfs-utils automake libxslt libxslt-devel

- name: add group for nginx
  group: name={{ GROUPID }} state=present system=yes

- name: add user for nginx
  user: name={{ USERID }} state=present system=yes group=nginx

- name: download nginx 
  get_url: url=http://nginx.org/download/{{ nginx_version }}.tar.gz dest=/tmp

- name: copy auto_install script
  copy: src=auto_install.sh dest=/tmp mode=0700

- name: auto install nginx 
  shell: /bin/bash /tmp/auto_install.sh

- name: copy nginx.service
  copy: src=nginx.service dest=/usr/lib/systemd/system/