- name: download tomcat8
  get_url: url=http://pan.ecarry.cc/software/apache-tomcat-8.5.63.tar.gz dest=/usr/local/

- name: unarchive tomcat
  unarchive: copy=no src=/usr/local/apache-tomcat-8.5.63.tar.gz dest=/usr/local/

- name: create symbolic link
  shell: ln -s /usr/local/apache-tomcat-8.5.63 /usr/local/tomcat