---
- name: configure ssh connection
  host: 
  gather_facts: false
  connection: local
  tasks:
    - name: configure ssh connection
      shell: |
        ssh-keyscan {{inventory_hostname}} >>~/.ssh/know_hosts
        sshpass -p'root123' ssh-copy-id root@{{inventory_hostname}}