---
- name: Install docker-compose
  get_url:
    url:  https://github.com/docker/compose/releases/download/{{ COMPOSE_VERSION }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0750
    state: file