version: "3.5"
services:
  mysql-server:
    image:  mysql:5.7
    container_name: mysql-server
    restart: unless-stopped
    command: --character-set-server=utf8 --collation-server=utf8_bin --sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --lower_case_table_names=1
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
    #ports:
      #- 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix-mysql:/var/lib/mysql:rw
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-${ZABBIX_VERSION}-latest
    container_name: zabbix-server-mysql
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
    ports:
      - 10051:10051
    links:
      - mysql-server
    depends_on:
      - mysql-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zabbix-server/conf:/etc/zabbix:ro
      - ./zabbix-server/alertscripts:/usr/lib/zabbix/alertscripts:ro
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-${ZABBIX_VERSION}-latest
    container_name: zabbix-web-nginx-mysql
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
      - PHP_TZ=Asia/Shanghai
    ports:
      - 80:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      #- ./fonts:/usr/share/zabbix/assets/fonts
    links:
      - mysql-server
      - zabbix-server-mysql
    depends_on:
      - mysql-server
      - zabbix-server-mysql